const REGISTER_USER = 'REGISTER_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const GET_PROFILE = 'GET_PROFILE';
const LOGIN_USER = 'LOGIN_USER';
const CREATE_PROFILE = 'CREATE_PROFILE';
const CLEAR_PROFILE = 'CLEAR_PROFILE';
const GET_PROFILES = 'GET_PROFILES';
const GET_PROFILES_BY_SKILLS = 'GET_PROFILES_BY_SKILLS';
const SET_THEME = 'SET_THEME';
const GET_THEME = 'GET_THEME';

export {
  REGISTER_USER,
  LOGOUT_USER,
  GET_PROFILE,
  CLEAR_PROFILE,
  SET_THEME,
  LOGIN_USER,
  GET_THEME,
  CREATE_PROFILE,
  GET_PROFILES,
  GET_PROFILES_BY_SKILLS
};
